### ISSUE TITLE
maxRange does not change after cells removed by RemoveMargin()?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [saeyslab/PeacoQC#20]
Hi there, 

I was able to `RemoveMargins()` of my flowFrame objects as in #12 (with minRange = -Inf, maxRange=2,000,000), but when I checked the maxRange of these objects, they look the same even though the cell numbers decreased. 

Would you mind helping me understand this?

Thank you for your help.

**BEFORE**

<img width="502" alt="Screenshot 2023-03-07 at 11 54 08" src="https://user-images.githubusercontent.com/62179082/223414871-f630f257-3a4f-4f19-bb1b-71bec505c781.png">

**AFTER**

<img width="513" alt="Screenshot 2023-03-07 at 11 54 20" src="https://user-images.githubusercontent.com/62179082/223414924-ee15704b-a759-474a-aea8-d4c10f9c2f8e.png">

**Comment by SofieVG** [comment]
These values are defined by the metadata stored in the FCS file, of the potential min and max as defined by the machine recording the data, and are typically not data-dependent.

**Comment by denvercal1234GitHub** [comment]
Hi @SofieVG -- Thank you very much for the clarification! 

I was able to confirm the max range with `flowCore::fsApply`.
