### ISSUE TITLE
A few edge case bugfixes

### ISSUE THREAD

**Issue by jacobpwagner** [saeyslab/PeacoQC#4]
Hello and thanks for your work on this.

I've come across a few weird edge case bugs that should have easy fixes.

1. If PeacoQC is run using a single channel for determining peaks, it errors out. The root of this appears to be [this line](https://github.com/saeyslab/PeacoQC/blob/34dfeb56864cf248147c4bfa21ebdba644552546/R/PeacoQC_helper_functions.R#L226). If `outlier_bins` is a single column, the subsetting there collapses to a vector which causes the subsequent [`apply` call](https://github.com/saeyslab/PeacoQC/blob/34dfeb56864cf248147c4bfa21ebdba644552546/R/PeacoQC_helper_functions.R#L230) to throw a dimension error:
```
Error in apply(peak_frame, 2, MADOutliers, MAD) :
  dim(X) must have a positive length
```
The culprit of course is every R programmer's (or at least my own) nemesis, `drop = TRUE`. So the solution is simple and seems to alleviate the problem.
```
peak_frame <- peaks[outlier_bins, , drop = FALSE]
```

2. Running PeacoQC with `plot = TRUE` appears to fail if there is not a valid time channel. The absence of a time channel seems to be accounted for in the [core PeacoQC functionality](https://github.com/saeyslab/PeacoQC/blob/34dfeb56864cf248147c4bfa21ebdba644552546/R/PeacoQC_helper_functions.R#L623-L628) and it seems the same thought was [given in the plotting functionality](https://github.com/saeyslab/PeacoQC/blob/34dfeb56864cf248147c4bfa21ebdba644552546/R/PlotPeacoQC_helper_functions.R#L36-L47). However, in the plotting case, `overview_blocks_time` is only defined in that `if` block, so if it isn't run, the [statement to return a list](https://github.com/saeyslab/PeacoQC/blob/34dfeb56864cf248147c4bfa21ebdba644552546/R/PlotPeacoQC_helper_functions.R#L49-L50) will error out with an undefined variable:
```
Error: object 'overview_blocks_time' not found
```

I'm also happy to submit a simple PR with those fixes if it would help.

**Comment by AnneliesEmmaneel** [comment]
Thank you for the fixes. I merged them now with the package. My apologies for the delay.
