### ISSUE TITLE
Error in which(res$to_split) : argument to 'which' is not logical

### ISSUE THREAD

**Issue by Diana-88a** [saeyslab/PeacoQC#8]
Hello,

I'm not sure just where to address this, but here goes. If I'm in the wrong place, just let me know.

I'm doing some exploratory work on some FCS data collected using the Cytek Aurora (spectral flow cytometer), and was looking at the differences between PeacoQC and flowAI. The idea is to first clean the data, send it to Harmony to attend to any batch effects, and then to FlowSOM and onward.

The data has first been gated in FlowJo for the cells of interest, then to eliminate doublets, and then living cells, before being exported and brought into R. It has been transformed by use of the Logicle function (flowCore) prior to sending it to PeacoQC.

The code looks like:

....
for(i in 1:20){
  ff <-fcs_logicle[[i]]
  
  channels=markerstotransform
  
  peacoqc_res <- PeacoQC(ff, channels, determine_good_cells = "all", 
                         IT_limit=0.6, MAD=3, save_fcs = TRUE, plot=TRUE, 
                         output_directory = "PeacoQCresults")
} 
....

from "Supplementary file R script spectral workflow" by H. den Braanker, 2021 (script.Rmd), and the results are:

(some 10 or more flowFrames have been done by now)
...
Plotting the results
Starting quality control analysis for c_pXXXXXXXX_SSC dd_live.fcs
Calculating peaks
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
Error in which(res$to_split) : argument to 'which' is not logical
In addition: Warning message:
In CheckInputSignalStability(ff, channels, determine_good_cells,  :
  There is an inconsistancy in the time channel.  It seems that not all the cells are ordered according to time in the flowframe.
>

First, what triggered the error and how can I get around it? For the time being, I'll take this FCS file out of the flowSet and continue. Another set of the data went through FlowJo with the addition of running flowAI in FlowJo prior to being exported. Although flowAI failed on a few of those FCS files, this one was not one of them.

The warning message I understand won't be enough to halt R, but the error is. Don't get me wrong: the warning is concerning, but from an earlier discussion it appears that PeacoQC will handle it anyway so I'm not that concerned (if you know what I mean). 

Thanks for any reply,

Diana

**Comment by phauchamps** [comment]
Hi @AnneliesEmmaneel , hi @KatrienQ,

I happen to have the same issue as Diana when running PeacoQC() on some fcs files. The error seems to happen a bit randomly, and is located in PeacoQC:::isolationTreeSD() when some obscure condition on the tree is true. I have just found that correcting the following line of code : 
_nodes_to_split <- which(res$to_split)_ 
into :
_nodes_to_split <- which(res$to_split == TRUE)_ 
as is done at other places in the code solves the issue. Somehow it seems that assigning TRUE or FALSE to an element of a dataframe does result in this element being encoded as a character and not as a logical.

Could you possibly correct and issue a bug fix asap ? 

Thanks !

Philippe

**Comment by phauchamps** [comment]
In fact the bug was due to side effect of an implicit conversion from logical to character.
I corrected the bug n my own fork and created pull request #9

**Comment by AnneliesEmmaneel** [comment]
Hi, thank you for locating and fixing these issues. I updated the code now.

**Comment by Diana-88a** [comment]
Hi,

I just checked the fix with files I had cleaned just this morning. The same fcs file tripped the error this morning so I checked it again, and it tripped it again this evening:

Starting quality control analysis for lgT_ C_xxxx.fcs
Calculating peaks
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
Error in which(res$to_split) : argument to 'which' is not logical

I made sure to update with the version on GitHub FYI.

Diana

**Comment by AnneliesEmmaneel** [comment]
Hi,

Can I ask you with what version of R you are working and which version of PeacoQC you have installed? 
I don't know if it is a possibility but I cannot reproduce the errors myself so I am wondering if you could share a file where the error occurs? Maybe if you anonymize everything it is possible?

Annelies

**Comment by Diana-88a** [comment]
RStudio 2022.02.3+492 "Prairie Trillium" Release (1db809b8323ba0a87c148d16eb84efe39a8e7785, 2022-05-16) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
R version: R 4.2.0 GUI 1.78 High Sierra build
PeacoQC version 1.7.1, as reported by RStudio

I am doing 20-30 files at a time, so here is my current code:

fcs_ctrls <- read.flowSet(path=fcs.dir, 
                          pattern="lgT_ C_.*\\.fcs", 
                          transformation=FALSE, 
                          truncate_max_range = FALSE)

IT_limit = 0.55
MAD = 6

for(i in 1:length(fcs_ctrls)){
  ff <- fcs_ctrls[[i]]
  
  channels=markerstotransform
  
  peacoqc_res_ctrls <- PeacoQC(ff, channels, determine_good_cells = "all", 
                         IT_limit=IT_limit, MAD=MAD, save_fcs = TRUE, plot=TRUE, 
                         output_directory = "PeacoQCresults_ctrls")
} 

My files are generally too big to allow for uploading on this site, but here's one that failed with the previous code.
[lgT_ C_live_CD45+.fcs copy.zip](https://github.com/saeyslab/PeacoQC/files/8912056/lgT_.C_live_CD45%2B.fcs.copy.zip)

Any help with this will be most appreciated. Thanks!

**Comment by Diana-88a** [comment]
I just finished running through the entire dataset. In the first instance (before the changes), I had 17 files that were rejected. In the second instance (after the changes), there were 16 files that were rejected. The odd thing is that there were only a few files that overlapped; some files that were rejected the first time worked after the fix, and some files that worked previously were subsequently rejected when rerun. Only seven files showed up in both.

One change in the two instances is that I found I needed to gate out a population from the data as it wasn't needed. This resulted in only a small change to the data, as the majority was positive for the marker anyway.

The data is (should be) anonymized, but it is from patient studies, so I'm hesitant to share publicly (in addition, it's not mine), so if we need to take it offline I'm for it.

**Comment by bpr4242** [comment]
I have the same issue still. Any updates?

**Comment by phauchamps** [comment]
Hi @AnneliesEmmaneel , hi @KatrienQ,

I found out that the PeacoQC Bioc github repo has not been updated with the code correction for this issue. Actually, there seems to be no update of the NEWS.md file in the Bioconductor PeacoQC repo since version 1.5, and current Bioc version is 1.9. Could you possibly port the latest updates to the Bioc repo as well ?  

Thanks,

Philippe

**Comment by AnneliesEmmaneel** [comment]
Hi, my apologies for the wait. I now pushed all the changes to the bioconductor development branch and updated the version number here as well. 

As for the which issue, if you still have issues in version 1.9.0, please let me know and inform me which packages you have loaded in. We are currently thinking that a wrong which function is being called (although I specifically specified the base package). I cannot repeat these errors and for a couple of colleagues, updating everything seemed to resolve the issue.

**Comment by phauchamps** [comment]
Thanks Annelies. I can indeed see the 1.9.0 version, including the fix, in Bioc devel branch. 
However, it would also be good to issue a bug fix on the RELEASE_3_16 branch, in order to incorporate the 1.9.0 fixes there as well, since next Bioc release will only be done in 4 months.
